### ISSUE TITLE
Exclude folders not working

### ISSUE THREAD

**Issue by maus258** [cboxdoerfer/fsearch#23]
Hi Christian,thanks for amazing fsearch.
In my case excluding folders not working(tested ntfs and ext4)

**Comment by cboxdoerfer** [comment]
Hi, thx for reporting.

I need a little more details to figure out what's going on:

What version do you use? The alpha or beta deb package? Or a build from master?

Can you paste all the config values of the [Database] section in `~/.config/fsearch/fsearch.conf`?

**Comment by maus258** [comment]
Using latest beta package

[Database]
update_database_on_launch=false
exclude_hidden_files_and_folders=false
follow_symbolic_links=false
location_1=/
exclude_location_1=/mnt/Storage/OneDrive
exclude_location_2=/mnt/Storage/Real-OneDrive
exclude_location_3=/mnt/Storage/Backups/Plasma/Plasma Apps/Dolphin

**Comment by cboxdoerfer** [comment]
Thx, I'll try to reproduce it when I get home

**Comment by cboxdoerfer** [comment]
Fixed on master. I'll publish a new build which will contain this fix in a few days.

**Comment by maus258** [comment]
Thanks!

**Comment by Futureknows** [comment]
I have a similar issue with lastest build compiled from git.
In my case, /home/timeshift is excluded.
All searches still show timeshift (which backs up everything so I see duplicates)

Fedora 31.
